# Generated by Django 5.2.12 on 2026-04-19 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('path', models.CharField(db_index=True, max_length=1000, unique=True)),
                ('media_type', models.CharField(db_index=True, max_length=10)),
                ('size', models.BigIntegerField(default=0)),
                ('duration', models.FloatField(default=0)),
                ('folder', models.CharField(max_length=1000)),
                ('modified', models.FloatField(default=0)),
                ('last_seen', models.FloatField(default=0)),
            ],
        ),
    ]
