# Generated by Django 5.2.12 on 2026-04-19 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_mediafile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='folder',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='path',
            field=models.CharField(db_index=True, max_length=2000, unique=True),
        ),
    ]
